config/routes.rb
Rails.application.routes.draw do
  resource :cookies,
           path: "/about/cookies",
           path_names: { edit: "/" },
           only: %i[edit update create]

  
  get "pages/:page", to: "pages#show"
  get "/404", to: "errors#not_found", via: :all
  get "/422", to: "errors#unprocessable_entity", via: :all
  get "/500", to: "errors#internal_server_error", via: :all
  get "/503", to: "errors#service_unavailable", via: :all

  # redirect no URL
  get  "" => redirect("/wizard/start")
  
  
  # redirect only the wizard
  get  "/wizard" => redirect("/wizard/start")
  
  # start page
  get  "/wizard/start", to: "wizard#start", via: :all
  get "/wizard/start_submit", to: "wizard#start_submit", via: :all

  # work_for_the_business page
  get "/wizard/work_for_the_business", to: "wizard#work_for_the_business", via: :all
  post "/wizard/work_for_the_business", to: "wizard#work_for_the_business_submit", via: :all

  # businesses page
  get  "/wizard/businesses", to: "wizard#businesses", via: :all
  post "/wizard/businesses", to: "wizard#businesses_submit", via: :all

  # business add page
  get  "/wizard/business/add", to: "wizard#business_add", via: :all
  post "/wizard/business/add", to: "wizard#business_add_submit", via: :all

  # business edit page
  get  "/wizard/business/edit", to: "wizard#business_edit", via: :all
  post "/wizard/business/edit", to: "wizard#business_edit_submit", via: :all

  # business remove action
  get "/wizard/business/remove", to: "wizard#business_remove", via: :all

  # what happened page
  get  "/wizard/what_happened", to: "wizard#what_happened", via: :all
  post "/wizard/what_happened", to: "wizard#what_happened_submit", via: :all

  # evidence page
  get  "/wizard/evidence", to: "wizard#evidence", via: :all
  post "/wizard/evidence", to: "wizard#evidence_submit", via: :all

  # evidence upload
  patch "/wizard/evidence/upload", to: "wizard#evidence_upload", via: :all

  # evidence remove
  get "/wizard/evidence/remove", to: "wizard#evidence_remove", via: :all

  # provide contact page
  get  "/wizard/include_contact", to: "wizard#include_contact", via: :all
  post "/wizard/include_contact", to: "wizard#include_contact_submit", via: :all

  # contact page
  get  "/wizard/contact", to: "wizard#contact", via: :all
  post "/wizard/contact", to: "wizard#contact_submit", via: :all

  # review
  get  "/wizard/review", to: "wizard#review", via: :all
  post "/wizard/review", to: "wizard#review_submit", via: :all

  # summary
  get  "/wizard/summary", to: "wizard#summary", via: :all

  # print
  get  "/wizard/print", to: "wizard#print", via: :all

  # not eligible
  get "/wizard/not_eligible", to: "wizard#not_eligible", via: :all


  # resubmit
  get "/resubmit", to: "resubmit#resubmit", via: :all
  post "/resubmit", to: "resubmit#resubmit_submit", via: :all

  # login
  get "/resubmit/login", to: "resubmit#login", via: :all
  post "/resubmit/login", to: "resubmit#login_submit", via: :all

  # login_failed
  get "/resubmit/login_failed", to: "resubmit#login_failed", via: :all

  # confirm
  get "/resubmit/confirm", to: "resubmit#confirm", via: :all
  post "/resubmit/confirm", to: "resubmit#confirm_submit", via: :all

  # resubmitted
  get "/resubmit/resubmitted", to: "resubmit#resubmitted", via: :all
  
  # not found
  get "/resubmit/not_found", to: "resubmit#not_found", via: :all

  # list
  get "/resubmit/list", to: "resubmit#list", via: :all

  # reports
  get "/reports", to: "reports#home", via: :all
  get "/reports/login", to: "reports#login", via: :all
  post "/reports/login", to: "reports#login_submit", via: :all
  get "/reports/logout", to: "reports#logout", via: :all
  get "/reports/menu", to: "reports#menu", via: :all
  get "/reports/report_summary", to: "reports#report_summary", via: :all
  get "/reports/report_summary_percent", to: "reports#report_summary_percent", via: :all

  get "/performance", to: "pages#performance", via: :all
end

app/controllers/resubmit_controller.rb
class ResubmitController < ApplicationController

    before_action :init, except: [:login, :login_submit, :login_failed]

    def login
        # shows the login form
    end

    def login_submit
        # processes login
        if params[:login][:access_code] == ENV["RESUBMIT_ACCESS_CODE"]
            session[:resubmit_access] = true
            redirect_to :controller => :resubmit, :action => :list
        else
            session[:resubmit_access] = nil
            redirect_to :controller => :resubmit, :action => :login_failed
        end
    end

    def login_failed
        # render that login failed

    end

    def resubmit
        # show the form
    end

    def resubmit_submit
        # takes data from the form and redirects to confirm
        @submission_id = params[:resubmission][:submission_id]
        redirect_to :controller => :resubmit, :action => :confirm, :submission_id => @submission_id and return
    end

    def confirm
        # fetches the appropriate record to render it
        @submission_id = params[:submission_id]
        begin
            @submission = Submission.find(@submission_id)
        rescue
            redirect_to :controller => :resubmit, :action => :not_found
        end
    end

    def not_found
        # tells the user the submission was not found
    end

    def confirm_submit
        # actions the resubmission
        #begin
            @submission = Submission.find(params[:resubmission][:submission_id])
            puts(params)
            Transmitter.Transmit(@submission)
            redirect_to :controller => :resubmit, :action => :resubmitted
        #rescue
        #    redirect_to :controller => :resubmit, :action => :not_found
        #end
    end

    def resubmitted
        # confirms the resubmission has happened
    end

    def list

        @submissions = Submission.where.not(:reference_number => nil).order(:created_at).last(100)
        

    end

private

    def init
        if session[:resubmit_access].nil?
            redirect_to :controller => :resubmit, :action => :login and return
        end
    end

end

app/views/resubmit/confirm.html.erb
<% title(t(".page_title")) %>

<h1 class="govuk-heading-xl"><%= t(".page_title") %></h1>

<dl class="govuk-summary-list govuk-!-margin-bottom-9">
    <div class="govuk-summary-list__row">
        <dt class="govuk-summary-list__key"><%= t(".reference_number") %></dt>
        <dd class="govuk-summary-list__value">
            <%= simple_format(@submission.reference_number) %>
        </dd>
    </div>
</dl>

<dl class="govuk-summary-list govuk-!-margin-bottom-9">
    <div class="govuk-summary-list__row">
        <dt class="govuk-summary-list__key"><%= t(".businesses") %></dt>
        <dd class="govuk-summary-list__value">
            <% @submission.businesses.each do |b| %>    
                <strong><%= b.business_name %></strong>
                <%= !b.business_address.blank?  ? raw("<br />") + b.business_address : nil %>
                <%= !b.business_postcode.blank? ? raw("<br />") + b.business_postcode : nil %>
                <%= !b.business_url.blank?      ? raw("<br />") + b.business_url : nil %>
                <%= raw("<br />") %>
            <% end %>
        </dd>
    </div>
</dl>

<dl class="govuk-summary-list govuk-!-margin-bottom-9">
    <div class="govuk-summary-list__row">
        <dt class="govuk-summary-list__key"><%= t(".what_happened") %></dt>
        <dd class="govuk-summary-list__value">
            <%= simple_format(@submission.what_happened) %>
        </dd>
    </div>
</dl>

<dl class="govuk-summary-list govuk-!-margin-bottom-9">
    <div class="govuk-summary-list__row">
        <dt class="govuk-summary-list__key"><%= t(".evidence") %></dt>
        <dd class="govuk-summary-list__value">
            <% if !@submission.evidence_files.blank? %>
                <% @submission.evidence_files.each do |ef| %>
                    <%= ef.filename %><br />
                <% end %>
            <% else %>
                <%= t(".no_evidence_files") %>
            <% end %>
        </dd>
    </div>
</dl>

<dl class="govuk-summary-list govuk-!-margin-bottom-9">
    <div class="govuk-summary-list__row">
        <dt class="govuk-summary-list__key"><%= t(".include_contact") %></dt>
        <dd class="govuk-summary-list__value">
            <%= t("." + @submission.include_contact) %>
        </dd>
    </div>
</dl>

<dl class="govuk-summary-list govuk-!-margin-bottom-9">
    <div class="govuk-summary-list__row">
        <dt class="govuk-summary-list__key"><%= t(".contact_name") %></dt>
        <dd class="govuk-summary-list__value">
            <%= !@submission.contact_name.blank? ? @submission.contact_name : t(".not_provided") %>
        </dd>
    </div>
</dl>

<dl class="govuk-summary-list govuk-!-margin-bottom-9">
    <div class="govuk-summary-list__row">
        <dt class="govuk-summary-list__key"><%= t(".contact_email_address") %></dt>
        <dd class="govuk-summary-list__value">
            <%= !@submission.contact_email_address.blank? ? @submission.contact_email_address : t(".not_provided") %>
        </dd>
    </div>
</dl>

<dl class="govuk-summary-list govuk-!-margin-bottom-9">
    <div class="govuk-summary-list__row">
        <dt class="govuk-summary-list__key"><%= t(".contact_telephone_number") %></dt>
        <dd class="govuk-summary-list__value">
            <%= !@submission.contact_telephone_number.blank? ? @submission.contact_telephone_number : t(".not_provided") %>
        </dd>
    </div>
</dl>

<%= form_for :resubmission, :url => resubmit_confirm_path, :method => :post  do |f| %>

    <%= f.hidden_field :submission_id, :value => @submission.id %>
    <%= f.govuk_submit t(".resubmit_button") , data: { disable_with: t(".resubmit_please_wait") } do %>
        <a class="govuk-button govuk-button--secondary" href="./list"><%= t(".cancel") %></a>
    <% end %>

<% end %>

app/views/resubmit/list.html.erb
<% title(t(".page_title")) %>

<h1 class="govuk-heading-xl"><%= t(".page_title") %></h1>

<%= t(".summary_html") %>

<table class="govuk-table">
    <thead class="govuk-table__head">
        <tr class="govuk-table__row">
            <th scope="col" class="govuk-table__header"><%= t(".reference_number") %></th>
            <th scope="col" class="govuk-table__header"><%= t(".created") %></th>
        </tr>
    </thead>
    <tbody class="govuk-table__body">

        <% @submissions.each do |s| %>

        <tr class="govuk-table__row">
            <th scope="row" class="govuk-table__header"><a href="./confirm?submission_id=<%= s.id %>"><%= s.reference_number %></a></th>
            <td class="govuk-table__cell"><%= s.created_at %></td>
        </tr>

        <% end %>

    </tbody>
</table>

app/views/resubmit/login.html.erb
<h1 class="govuk-heading-xl"><%= t(".page_title") %></h1>

<%= t(".summary_html") %>

<%= form_for :login, :url => resubmit_login_path, :method => :post  do |f| %>

    <%= f.govuk_text_field :access_code, label: { text: t(".access_code") }, width: "two-thirds" %>
    
    <%= f.govuk_submit t(".login") %>

<% end %>

app/views/resubmit/login_failed.html.erb
<h1 class="govuk-heading-xl"><%= t(".page_title") %></h1>

<%= t(".summary_html") %>

app/views/resubmit/not_found.html.erb
<% title(t(".page_title")) %>

<h1 class="govuk-heading-xl"><%= t(".page_title") %></h1>
<%= t(".summary_html") %>

app/views/resubmit/resubmit.html.erb
<% title(t(".page_title")) %>

<h1 class="govuk-heading-xl"><%= t(".page_title") %></h1>

<%= t(".summary_html") %>

<%= form_for :resubmission, :url => resubmit_path, :method => :post  do |f| %>

    <%= f.govuk_text_field :submission_id, label: { text: t(".submission_id") }, width: "two-thirds" %>
    
    <%= f.govuk_submit %>

<% end %>

app/views/resubmit/resubmitted.html.erb
<% title(t(".page_title")) %>

<h1 class="govuk-heading-xl"><%= t(".page_title") %>

<%= t(".summary_html") %>