config/routes.rb
Rails.application.routes.draw do
  resource :cookies,
           path: "/about/cookies",
           path_names: { edit: "/" },
           only: %i[edit update create]

  
  get "pages/:page", to: "pages#show"
  get "/404", to: "errors#not_found", via: :all
  get "/422", to: "errors#unprocessable_entity", via: :all
  get "/500", to: "errors#internal_server_error", via: :all
  get "/503", to: "errors#service_unavailable", via: :all

  # redirect no URL
  get  "" => redirect("/wizard/start")
  
  
  # redirect only the wizard
  get  "/wizard" => redirect("/wizard/start")
  
  # start page
  get  "/wizard/start", to: "wizard#start", via: :all
  get "/wizard/start_submit", to: "wizard#start_submit", via: :all

  # work_for_the_business page
  get "/wizard/work_for_the_business", to: "wizard#work_for_the_business", via: :all
  post "/wizard/work_for_the_business", to: "wizard#work_for_the_business_submit", via: :all

  # businesses page
  get  "/wizard/businesses", to: "wizard#businesses", via: :all
  post "/wizard/businesses", to: "wizard#businesses_submit", via: :all

  # business add page
  get  "/wizard/business/add", to: "wizard#business_add", via: :all
  post "/wizard/business/add", to: "wizard#business_add_submit", via: :all

  # business edit page
  get  "/wizard/business/edit", to: "wizard#business_edit", via: :all
  post "/wizard/business/edit", to: "wizard#business_edit_submit", via: :all

  # business remove action
  get "/wizard/business/remove", to: "wizard#business_remove", via: :all

  # what happened page
  get  "/wizard/what_happened", to: "wizard#what_happened", via: :all
  post "/wizard/what_happened", to: "wizard#what_happened_submit", via: :all

  # evidence page
  get  "/wizard/evidence", to: "wizard#evidence", via: :all
  post "/wizard/evidence", to: "wizard#evidence_submit", via: :all

  # evidence upload
  patch "/wizard/evidence/upload", to: "wizard#evidence_upload", via: :all

  # evidence remove
  get "/wizard/evidence/remove", to: "wizard#evidence_remove", via: :all

  # provide contact page
  get  "/wizard/include_contact", to: "wizard#include_contact", via: :all
  post "/wizard/include_contact", to: "wizard#include_contact_submit", via: :all

  # contact page
  get  "/wizard/contact", to: "wizard#contact", via: :all
  post "/wizard/contact", to: "wizard#contact_submit", via: :all

  # review
  get  "/wizard/review", to: "wizard#review", via: :all
  post "/wizard/review", to: "wizard#review_submit", via: :all

  # summary
  get  "/wizard/summary", to: "wizard#summary", via: :all

  # print
  get  "/wizard/print", to: "wizard#print", via: :all

  # not eligible
  get "/wizard/not_eligible", to: "wizard#not_eligible", via: :all


  # resubmit
  get "/resubmit", to: "resubmit#resubmit", via: :all
  post "/resubmit", to: "resubmit#resubmit_submit", via: :all

  # login
  get "/resubmit/login", to: "resubmit#login", via: :all
  post "/resubmit/login", to: "resubmit#login_submit", via: :all

  # login_failed
  get "/resubmit/login_failed", to: "resubmit#login_failed", via: :all

  # confirm
  get "/resubmit/confirm", to: "resubmit#confirm", via: :all
  post "/resubmit/confirm", to: "resubmit#confirm_submit", via: :all

  # resubmitted
  get "/resubmit/resubmitted", to: "resubmit#resubmitted", via: :all
  
  # not found
  get "/resubmit/not_found", to: "resubmit#not_found", via: :all

  # list
  get "/resubmit/list", to: "resubmit#list", via: :all

  # reports
  get "/reports", to: "reports#home", via: :all
  get "/reports/login", to: "reports#login", via: :all
  post "/reports/login", to: "reports#login_submit", via: :all
  get "/reports/logout", to: "reports#logout", via: :all
  get "/reports/menu", to: "reports#menu", via: :all
  get "/reports/report_summary", to: "reports#report_summary", via: :all
  get "/reports/report_summary_percent", to: "reports#report_summary_percent", via: :all

  get "/performance", to: "pages#performance", via: :all
end

app/controllers/wizard_controller.rb
class WizardController < ApplicationController
    
    before_action :init

    def start

        redirect_to :controller => :wizard, :action => :start_submit and return

    end

    def start_submit

        # Create the new submission
        session[:submission_id] = nil

        @submission = Submission.new
        @submission.status = :start
        @submission.router.set_visited(:start)
        @submission.router.set_completed(:start)
                
        redirect_to :controller => :wizard, :action => @submission.router.next_page(:start) and return
        
    end

    def work_for_the_business

        # record arrival at page
        @submission.router.set_visited(:work_for_the_business)
        @submission.status = :work_for_the_business
        @submission.save(:validate => false)

    end

    def work_for_the_business_submit

        puts @submission.inspect

        # if the submission doesn't exist yet, update it and save it
        if session[:submission_id].nil?

            @submission = Submission.new
            @submission.router.set_visited(:start)
            @submission.router.set_completed(:start)
            @submission.router.set_visited(:work_for_the_business)
            @submission.status = :work_for_the_business
            @submission.save(:validate => false)

            session[:submission_id] = @submission.id
        end

        if @submission.update(params.require(:submission).permit(:work_for_the_business))

            # record submit happened
            @submission.router.set_completed(:work_for_the_business)
            @submission.status = :work_for_the_business
            @submission.save(:validate => false)

            # depending on yes or no, go to next page or not_eligible page
            if @submission.work_for_the_business == "yes"
                redirect_to :controller => :wizard, :action => @submission.router.next_page(:work_for_the_business) and return
            else
                redirect_to :controller => :wizard, :action => :not_eligible and return
            end

        else
            render :work_for_the_business and return
        end

    end






    def businesses

        # record arrival at page
        @submission.router.set_visited(:businesses)
        @submission.status = :businesses
        @submission.save(:validate => false)

    end

    def businesses_submit

        # did we add a business?
        if @submission.businesses.count > 0

            # record submit happened
            @submission.router.set_completed(:businesses)
            @submission.status = :businesses
            @submission.save(:validate => false)
            
            redirect_to :controller => :wizard, :action => @submission.router.next_page(:businesses) and return

        else
            @submission.errors.add(:businesses, I18n.t("errors.businesses.no_businesses"))
            render :businesses
        end

    end

    def business_add
        @business = @submission.businesses.new
    end

    def business_add_submit

        # save the business
        @business = @submission.businesses.new(params.require(:business).permit(:submission_id, :business_name, :business_address, :business_postcode, :business_url))
        if @business.save
            redirect_to :controller => :wizard, :action => :businesses and return
        else            
            render :business_add and return
        end
    end

    def business_edit
        @business = @submission.businesses.where(id: params[:business_id]).first
    end

    def business_edit_submit
        @business = @submission.businesses.where(id: params[:business][:id]).first
        if @business.update(params.require(:business).permit(:submission_id, :id, :business_name, :business_address, :business_postcode, :business_url))
            redirect_to :controller => :wizard, :action => :businesses and return
        else
            render :business_edit and return
        end
    end

    def business_remove
        @business = @submission.businesses.where(id: params[:business_id]).first
        if !@business.nil?
            @business.destroy
        end
        redirect_to :controller => :wizard, :action => :businesses, :method => 'GET' and return
    end




    def what_happened
        # record arrival at page
        @submission.router.set_visited(:what_happened)
        @submission.status = :what_happened
        @submission.save(:validate => false)
    end

    def what_happened_submit
        
        if @submission.update(params.require(:submission).permit(:what_happened))

            # record submit happened
            @submission.router.set_completed(:what_happened)
            @submission.status = :what_happened
            @submission.save(:validate => false)

            redirect_to :controller => :wizard, :action => @submission.router.next_page(:what_happened) and return

        else
            render :what_happened and return
        end

    end



    def evidence
        # record arrival at page
        @submission.router.set_visited(:evidence)
        @submission.status = :evidence
        @submission.save(:validate => false)
    end

    def evidence_submit
        
        # record submit happened
        @submission.router.set_completed(:evidence)
        @submission.status = :evidence
        @submission.save(:validate => false)

        redirect_to :controller => :wizard, :action => @submission.router.next_page(:evidence) and return

    end

    def evidence_upload

        if !params[:submission].nil?
            if @submission.valid_file?(params[:submission][:evidence_files])
                @submission.evidence_files.attach(params[:submission][:evidence_files])
                redirect_to :controller => :wizard, :action => :evidence and return
            else
                render :evidence and return
            end
        else
            @submission.errors.add(:evidencefiles, I18n.t("errors.upload.no_file_error_message"))
            render :evidence and return
        end

    end

    def evidence_remove

        @evidence_file = @submission.evidence_files.where(id: params[:evidence_id]).first
        if !@evidence_file.nil?
            @evidence_file.purge
            redirect_to :controller => :wizard, :action => :evidence and return
        else
            render :evidence and return
        end

    end

    def include_contact

        # record arrival at page
        @submission.router.set_visited(:include_contact)
        @submission.status = :include_contact
        @submission.save(:validate => false)

    end
    
    def include_contact_submit

        if !params[:submission][:include_contact].blank?

            # record submit happened
            @submission.router.set_completed(:include_contact)
            @submission.status = :include_contact
            @submission.include_contact = params[:submission][:include_contact]

            # change the page sequence to include the contact page or not
            if @submission.include_contact == "yes"

                # inject the contact page into the router if it's not already there
                if @submission.router.step(:contact).nil?
                    @submission.router.add_page(:contact)
                end
                
            else

                # clear the contact details
                @submission.contact_name = nil
                @submission.contact_email_address = nil
                @submission.contact_telephone_number = nil

                # remove the contact page from the router
                @submission.router.remove_page(:contact)

            end

            @submission.save(:validate => false)

            redirect_to :controller => :wizard, :action => @submission.router.next_page(:include_contact) and return

        else

            @submission.errors.add(:include_contact, I18n.t("errors.include_contact.no_option_chosen"))
            render :include_contact and return

        end

    end

    def contact

        # record arrival at page
        @submission.router.set_visited(:contact)
        @submission.status = :contact
        @submission.save(:validate => false)

    end

    def contact_submit

        if @submission.update(params.require(:submission).permit(:contact_name, :contact_email_address, :contact_telephone_number))

            # record submit happened
            @submission.router.set_completed(:contact)
            @submission.status = :contact
            @submission.save(:validate => false)

            redirect_to :controller => :wizard, :action => @submission.router.next_page(:contact) and return

        else
            render :contact and return
        end

    end

    def review
        # record arrival at page
        @submission.router.set_visited(:review)
        @submission.status = :review
        @submission.save(:validate => false)
    end

    def review_submit

        # todo - transmit!

        # record submit happened
        @submission.router.set_completed(:review)
        @submission.status = :review
        @submission.save(:validate => false)

        # calculate the new reference_index and reference_number
        @reference_index = Submission.maximum("reference_index")
        if @reference_index.nil?
            @reference_index = 1
        else
            @reference_index += 1
        end

        # update the submission
        @submission.reference_index = @reference_index
        @submission.reference_number = "CMA-MWR-" + @reference_index.to_s.rjust(5,"0")
        @submission.save(:validate => false)

        # transmit the data
        Transmitter.Transmit(@submission)
        @submission.save(:validate => false)

        # Send a notification if required
        Notifier.Send(@submission) if @submission.contact_email_address.present?
        
        redirect_to :controller => :wizard, :action => @submission.router.next_page(:review) and return

    end
    
    def summary

app/views/wizard/business_add.html.erb
<% title(t(".page_title")) %>

<div class="govuk-width-container">

    <%= link_to t("link.back"), wizard_businesses_path, class: "govuk-back-link ga-pageLink" %>

    <main class="govuk-main-wrapper">
        <div class="govuk-grid-row">
            <div class="govuk-grid-column-two-thirds">

            <%= form_for @business, :url => wizard_business_add_path, :method => :post  do |f| %>

                <%= f.govuk_error_summary %>
                
                <%= f.govuk_fieldset legend: { text: t(".page_title"), size: "xl" } do %>
                
                    <%= f.govuk_text_field :business_name,     label: { text: t(".business_name") }, width: "two-thirds" %>
                    <%= f.govuk_text_area  :business_address,  label: { text: t(".business_address") }, width: "two-thirds",  rows: 5 %>
                    <%= f.govuk_text_field :business_postcode, label: { text: t(".business_postcode") }, width: "two-thirds" %>
                    <%= f.govuk_text_field :business_url,      label: { text: t(".business_url") }, hint: {text: t(".business_url_hint")}, width: "two-thirds" %>
                    
                <% end %>

                <%= f.govuk_submit t(".submit") do %>
                    <a class="govuk-button govuk-button--secondary" href="<%= wizard_businesses_path %>"><%= t(".cancel") %></a>
                <% end %>

                

            <% end %>

            </div>
        </div>
    </main>
</div>

app/views/wizard/business_edit.html.erb
<% title(t(".page_title")) %>

<div class="govuk-width-container">

    <%= link_to t("link.back"), wizard_businesses_path, class: "govuk-back-link ga-pageLink" %>

    <main class="govuk-main-wrapper">
        <div class="govuk-grid-row">
            <div class="govuk-grid-column-two-thirds">

            <%= form_for @business, :url => wizard_business_edit_path, :method => :post  do |f| %>
                
                <%= f.govuk_error_summary %>
                
                <%= f.hidden_field :id %>

                <%= f.govuk_fieldset legend: { text: t(".page_title"),size: "xl" } do %>
                    
                    <%= f.govuk_text_field :business_name,     label: { text: t(".business_name") },     width: "two-thirds" %>
                    <%= f.govuk_text_area  :business_address,  label: { text: t(".business_address") },  width: "two-thirds",  rows: 5 %>
                    <%= f.govuk_text_field :business_postcode, label: { text: t(".business_postcode") }, width: "two-thirds" %>
                    <%= f.govuk_text_field :business_url,      label: { text: t(".business_url") }, hint: {text: t(".business_url_hint")}, width: "two-thirds" %>

                <% end %>

                <%= f.govuk_submit t(".submit") do %>
                    <a class="govuk-button govuk-button--secondary" href="<%= wizard_businesses_path %>"><%= t(".cancel") %></a>
                <% end %>

            <% end %>

            </div>
        </div>
    </main>
</div>

app/views/wizard/businesses.html.erb
<% title(t(".page_title")) %>

<div class="govuk-width-container">

    <%= link_to t("link.back"), "/wizard/" + @submission.router.previous_page(:businesses).to_s , class: "govuk-back-link ga-pageLink" %>

    <main class="govuk-main-wrapper">
        <div class="govuk-grid-row">
            <div class="govuk-grid-column-two-thirds">

                <h1 class="govuk-heading-xl"><%= t(".page_title") %></h1>

                <%= t(".body_html") %>

                <%= form_for @submission, url: wizard_businesses_path, method: :post do |f| %>
                    <%= f.govuk_error_summary %>
                <% end %>

                <% if @submission.businesses.count > 0 %>

                    <table class="govuk-table">
                    <caption class="govuk-table__caption govuk-table__caption--m"><%= t(".business_details") %></caption>
                    <thead class="govuk-table__head">
                        <tr class="govuk-table__row">
                            <th scope="col" class="govuk-table__header" width="20%"><%= t(".business_name") %></th>
                            <th scope="col" class="govuk-table__header" width="40%"><%= t(".business_address") %></th>
                            <th scope="col" class="govuk-table__header" width="20%"><%= t(".business_postcode") %></th>
                            <th scope="col" class="govuk-table__header" width="20%">&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody class="govuk-table__body">
                        <% @submission.businesses.each do |b| %>
                        <tr class="govuk-table__row">
                            <th scope="row" class="govuk-table__header"><%= b.business_name %></th>
                            <td class="govuk-table__cell"><%= b.business_address.gsub("\r\n",", ") %></td>
                            <td class="govuk-table__cell"><%= b.business_postcode %></td>
                            <td class="govuk-table__cell"><a href="./business/edit/?business_id=<%= b.id %>"><%= t('.change') %></a>&nbsp;&nbsp;<a href="./business/remove/?business_id=<%= b.id %>"><%= t('.remove') %></a></td>
                        </tr>
                        <% end %>
                    </tbody>
                    </table>

                <% else %>
                    <p class="govuk-body">No businesses have been added yet.</p>
                <% end %>

                <%= form_for @submission, url: wizard_business_add_path, method: :get do |f| %>
                    <%= f.govuk_submit t(".add_business"), secondary:true %>
                <% end %>

                <%= form_for @submission, url: wizard_businesses_path, method: :post do |f| %>
                    <%= f.govuk_submit %>
                <% end %>

            </div>
        </div>
    </main>
</div>

app/views/wizard/evidence.html.erb
<% title(t(".page_title")) %>

<div class="govuk-width-container">

    <%= link_to t("link.back"), "/wizard/" + @submission.router.previous_page(:evidence).to_s , class: "govuk-back-link ga-pageLink" %>

    <main class="govuk-main-wrapper">
        <div class="govuk-grid-row">
            <div class="govuk-grid-column-two-thirds">

            <%= form_for @submission, url: wizard_evidence_upload_path do |f| %>

                <%= f.govuk_error_summary %>
                
                <%= f.govuk_file_field :evidence_files,
                    accept: ".txt, .doc, .docx, .xls, .xlsx, .ppt, .pptx, .pdf, image/jpg, image/png, .mp4, .mov, .wmv",
                    multiple:false,
                    enctype: "multipart/form-data",
                    class: "upload-input",
                    label: {text: t(".page_title"), size: "xl" },
                    hint:  {text: t(".hint_html") }
                    %>

                <%= f.govuk_submit t(".upload_file"), secondary:true, classes: "upload-files-button"%>
                    
            <% end %>

            <% if @submission.evidence_files.length > 0 %>
            <table class="govuk-table">
                <thead class="govuk-table__head">
                    <tr class="govuk-table__row">
                        <th class="govuk-table__header"><%= t(".filename") %></th>
                        <th class="govuk-table__header"><%= t(".filesize") %></th>
                        <th class="govuk-table__header"><%= t(".action") %></th>
                    </tr>
                </thead>
                <tbody class="govuk-table__body">
                    <% if @submission.evidence_files.length > 0 %>
                        <% @submission.evidence_files.each do |ef| %>
                        <tr class="govuk-table__row">
                            <td class="govuk-table__cell"><%= ef.filename %></td>
                            <td class="govuk-table__cell"><%= number_to_human_size(ef.byte_size) %></td>
                            <td class="govuk-table__cell"><a href="<%= wizard_evidence_remove_path %>?evidence_id=<%= ef.id %>"><%= t(".remove") %></a></td>
                        </tr>
                        <% end %>
                    <% else %>
                        <tr><td class="govuk-table__cell" colspan="3"><%= t(".no_files") %></td></tr>
                    <% end %>
                </tbody>
            </table>
            <% end %>

            <%= form_for @submission, url: wizard_evidence_path, method: :post do |f| %>
                <%= f.govuk_submit classes: "upload-continue-button" %>
            <% end %>

            </div>
        </div>
    </main>
</div>

app/views/wizard/include_contact.html.erb
<% title(t(".page_title")) %>

<div class="govuk-width-container">

    <%= link_to t("link.back"), "/wizard/" + @submission.router.previous_page(:include_contact).to_s , class: "govuk-back-link ga-pageLink" %>

    <main class="govuk-main-wrapper">
        <div class="govuk-grid-row">
            <div class="govuk-grid-column-two-thirds">

            <%= form_for @submission, url: wizard_include_contact_path, method: :post do |f| %>
                    
              <%
              options = [
                OpenStruct.new(id: "yes", name: "Yes"),
                OpenStruct.new(id: "no", name: "No"),
              ]
              %>

              <%= f.govuk_collection_radio_buttons :include_contact, options, :id, :name, legend: { text: t(".page_title"), size: "xl" }, hint: { text: t(".hint_html") } %>

              <%= f.govuk_submit %>
                
            <% end %>

            </div>
        </div>
    </main>
</div>

app/views/wizard/review.html.erb
<% title(t(".page_title")) %>

<div class="govuk-width-container">
    <main class="govuk-main-wrapper">
        <div class="govuk-grid-row">
            <div class="govuk-grid-column-two-thirds">

                <h1 class="govuk-heading-xl"><%= t(".page_title") %></h1>

                <%= t(".body_html") %>

                <dl class="govuk-summary-list govuk-!-margin-bottom-9">
                    <div class="govuk-summary-list__row">
                        <dt class="govuk-summary-list__key"><%= t(".work_for_the_business") %></dt>
                        <dd class="govuk-summary-list__value">
                            <%= t("." + @submission.work_for_the_business) %>
                        </dd>
                        <dd class="govuk-summary-list__actions">
                            <%= link_to wizard_work_for_the_business_path, class: "govuk-link", title: "Change #{t(".work_for_the_business").downcase}" do %>
                                Change<span class="govuk-visually-hidden"> <%= t(".work_for_the_business").downcase %></span>
                            <% end %>
                        </dd>
                    </div>
                </dl>

                <dl class="govuk-summary-list govuk-!-margin-bottom-9">
                    <div class="govuk-summary-list__row">
                        <dt class="govuk-summary-list__key"><%= t(".businesses") %></dt>
                        <dd class="govuk-summary-list__value">
                            <% @submission.businesses.each do |b| %>    
                                <strong><%= b.business_name %></strong>
                                <%= !b.business_address.blank?  ? raw("<br />") + b.business_address : nil %>
                                <%= !b.business_postcode.blank? ? raw("<br />") + b.business_postcode : nil %>
                                <%= !b.business_url.blank?      ? raw("<br />") + b.business_url : nil %>
                                <%= raw("<br />") %>
                            <% end %>
                        </dd>
                        <dd class="govuk-summary-list__actions">
                            <%= link_to wizard_businesses_path, class: "govuk-link", title: "Change #{t(".businesses").downcase}" do %>
                                Change<span class="govuk-visually-hidden"> <%= t(".business").downcase %></span>
                            <% end %>
                        </dd>
                    </div>
                </dl>

                <dl class="govuk-summary-list govuk-!-margin-bottom-9">
                    <div class="govuk-summary-list__row">
                        <dt class="govuk-summary-list__key"><%= t(".what_happened") %></dt>
                        <dd class="govuk-summary-list__value">
                            <%= simple_format(@submission.what_happened) %>
                        </dd>
                        <dd class="govuk-summary-list__actions">
                            <%= link_to wizard_what_happened_path, class: "govuk-link", title: "Change #{t(".what_happened").downcase}" do %>
                                Change<span class="govuk-visually-hidden"> <%= t(".what_happened").downcase %></span>
                            <% end %>
                        </dd>
                    </div>
                </dl>

                <dl class="govuk-summary-list govuk-!-margin-bottom-9">
                    <div class="govuk-summary-list__row">
                        <dt class="govuk-summary-list__key"><%= t(".evidence") %></dt>
                        <dd class="govuk-summary-list__value">
                            <% if !@submission.evidence_files.blank? %>
                                <% @submission.evidence_files.each do |ef| %>
                                    <%= ef.filename %><br />
                                <% end %>
                            <% else %>
                                <%= t(".no_evidence_files") %>
                            <% end %>
                        </dd>
                        <dd class="govuk-summary-list__actions">
                            <%= link_to wizard_evidence_path, class: "govuk-link", title: "Change #{t(".evidence").downcase}" do %>
                                Change<span class="govuk-visually-hidden"> <%= t(".evidence").downcase %></span>
                            <% end %>
                        </dd>
                    </div>
                </dl>

                <dl class="govuk-summary-list govuk-!-margin-bottom-9">
                    <div class="govuk-summary-list__row">
                        <dt class="govuk-summary-list__key"><%= t(".include_contact") %></dt>
                        <dd class="govuk-summary-list__value">
                            <%= t("." + @submission.include_contact) %>
                        </dd>
                        <dd class="govuk-summary-list__actions">
                            <%= link_to wizard_include_contact_path, class: "govuk-link", title: "Change #{t(".include_contact").downcase}" do %>
                                Change<span class="govuk-visually-hidden"> <%= t(".include_contact").downcase %></span>
                            <% end %>
                        </dd>
                    </div>
                </dl>


                <dl class="govuk-summary-list govuk-!-margin-bottom-9">
                    <div class="govuk-summary-list__row">
                        <dt class="govuk-summary-list__key"><%= t(".contact_name") %></dt>
                        <dd class="govuk-summary-list__value">
                            <%= !@submission.contact_name.blank? ? @submission.contact_name : t(".not_provided") %>
                        </dd>
                        <dd class="govuk-summary-list__actions">
                            <%= link_to wizard_contact_path, class: "govuk-link", title: "Change #{t(".contact").downcase}" do %>
                                Change<span class="govuk-visually-hidden"> <%= t(".contact").downcase %></span>
                            <% end %>
                        </dd>
                    </div>
                </dl>

                <dl class="govuk-summary-list govuk-!-margin-bottom-9">
                    <div class="govuk-summary-list__row">
                        <dt class="govuk-summary-list__key"><%= t(".contact_email_address") %></dt>
                        <dd class="govuk-summary-list__value">
                            <%= !@submission.contact_email_address.blank? ? @submission.contact_email_address : t(".not_provided") %>
                        </dd>
                        <dd class="govuk-summary-list__actions">
                            <%= link_to wizard_contact_path, class: "govuk-link", title: "Change #{t(".contact").downcase}" do %>
                                Change<span class="govuk-visually-hidden"> <%= t(".contact").downcase %></span>
                            <% end %>
                        </dd>
                    </div>
                </dl>

                <dl class="govuk-summary-list govuk-!-margin-bottom-9">
                    <div class="govuk-summary-list__row">
                        <dt class="govuk-summary-list__key"><%= t(".contact_telephone_number") %></dt>
                        <dd class="govuk-summary-list__value">
                            <%= !@submission.contact_telephone_number.blank? ? @submission.contact_telephone_number : t(".not_provided") %>
                        </dd>
                        <dd class="govuk-summary-list__actions">
                            <%= link_to wizard_contact_path, class: "govuk-link", title: "Change #{t(".contact").downcase}" do %>
                                Change<span class="govuk-visually-hidden"> <%= t(".contact").downcase %></span>
                            <% end %>
                        </dd>
                    </div>
                </dl>

                <%= form_for @submission, url: wizard_review_path, method: :post do |f| %>
                    <%= f.govuk_submit t(".submit_button"), data: { disable_with: t(".submit_please_wait") } %>
                <% end %>

            </div>
        </div>
    </main>
</div>

app/views/wizard/test.html.erb
<% title("Test") %>

<pre>
<%= Transmitter.BuildJSON(@submission) %>
</pre>