config/routes.rb
Rails.application.routes.draw do
  resource :cookies,
           path: "/about/cookies",
           path_names: { edit: "/" },
           only: %i[edit update create]

  
  get "pages/:page", to: "pages#show"
  get "/404", to: "errors#not_found", via: :all
  get "/422", to: "errors#unprocessable_entity", via: :all
  get "/500", to: "errors#internal_server_error", via: :all
  get "/503", to: "errors#service_unavailable", via: :all

  # redirect no URL
  get  "" => redirect("/wizard/start")
  
  
  # redirect only the wizard
  get  "/wizard" => redirect("/wizard/start")
  
  # start page
  get  "/wizard/start", to: "wizard#start", via: :all
  get "/wizard/start_submit", to: "wizard#start_submit", via: :all

  # work_for_the_business page
  get "/wizard/work_for_the_business", to: "wizard#work_for_the_business", via: :all
  post "/wizard/work_for_the_business", to: "wizard#work_for_the_business_submit", via: :all

  # businesses page
  get  "/wizard/businesses", to: "wizard#businesses", via: :all
  post "/wizard/businesses", to: "wizard#businesses_submit", via: :all

  # business add page
  get  "/wizard/business/add", to: "wizard#business_add", via: :all
  post "/wizard/business/add", to: "wizard#business_add_submit", via: :all

  # business edit page
  get  "/wizard/business/edit", to: "wizard#business_edit", via: :all
  post "/wizard/business/edit", to: "wizard#business_edit_submit", via: :all

  # business remove action
  get "/wizard/business/remove", to: "wizard#business_remove", via: :all

  # what happened page
  get  "/wizard/what_happened", to: "wizard#what_happened", via: :all
  post "/wizard/what_happened", to: "wizard#what_happened_submit", via: :all

  # evidence page
  get  "/wizard/evidence", to: "wizard#evidence", via: :all
  post "/wizard/evidence", to: "wizard#evidence_submit", via: :all

  # evidence upload
  patch "/wizard/evidence/upload", to: "wizard#evidence_upload", via: :all

  # evidence remove
  get "/wizard/evidence/remove", to: "wizard#evidence_remove", via: :all

  # provide contact page
  get  "/wizard/include_contact", to: "wizard#include_contact", via: :all
  post "/wizard/include_contact", to: "wizard#include_contact_submit", via: :all

  # contact page
  get  "/wizard/contact", to: "wizard#contact", via: :all
  post "/wizard/contact", to: "wizard#contact_submit", via: :all

  # review
  get  "/wizard/review", to: "wizard#review", via: :all
  post "/wizard/review", to: "wizard#review_submit", via: :all

  # summary
  get  "/wizard/summary", to: "wizard#summary", via: :all

  # print
  get  "/wizard/print", to: "wizard#print", via: :all

  # not eligible
  get "/wizard/not_eligible", to: "wizard#not_eligible", via: :all


  # resubmit
  get "/resubmit", to: "resubmit#resubmit", via: :all
  post "/resubmit", to: "resubmit#resubmit_submit", via: :all

  # login
  get "/resubmit/login", to: "resubmit#login", via: :all
  post "/resubmit/login", to: "resubmit#login_submit", via: :all

  # login_failed
  get "/resubmit/login_failed", to: "resubmit#login_failed", via: :all

  # confirm
  get "/resubmit/confirm", to: "resubmit#confirm", via: :all
  post "/resubmit/confirm", to: "resubmit#confirm_submit", via: :all

  # resubmitted
  get "/resubmit/resubmitted", to: "resubmit#resubmitted", via: :all
  
  # not found
  get "/resubmit/not_found", to: "resubmit#not_found", via: :all

  # list
  get "/resubmit/list", to: "resubmit#list", via: :all

  # reports
  get "/reports", to: "reports#home", via: :all
  get "/reports/login", to: "reports#login", via: :all
  post "/reports/login", to: "reports#login_submit", via: :all
  get "/reports/logout", to: "reports#logout", via: :all
  get "/reports/menu", to: "reports#menu", via: :all
  get "/reports/report_summary", to: "reports#report_summary", via: :all
  get "/reports/report_summary_percent", to: "reports#report_summary_percent", via: :all

  get "/performance", to: "pages#performance", via: :all
end

app/views/layouts/_analytics.html.erb
<script async src="https://www.googletagmanager.com/gtag/js?id=<%= analytics_tracking_id %>"></script>
<script>
  <% unless cookie_settings['analytics'] %>
  window["ga-disable-<%= analytics_tracking_id %>"] = true
  <% end %>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}   
  gtag('js', new Date());

  gtag('config', '<%= analytics_tracking_id %>', {'anonymize_ip': true});
</script>

app/views/layouts/_cookie_banner.html.erb
<div class="govuk-cookie-banner " role="region" aria-label="Cookies on <%= service_name %>">
  <div class="govuk-cookie-banner__message govuk-width-container">

    <div class="govuk-grid-row">
      <div class="govuk-grid-column-two-thirds">
        <h2 class="govuk-cookie-banner__heading govuk-heading-m">Cookies on <%= service_name %></h2>

        <div class="govuk-cookie-banner__content">
          <p>We use some essential cookies to make this service work.</p>
          <p>We'd also like to use analytics cookies so we can understand how you use the service and make improvements to government services.</p>
        </div>
      </div>
    </div>

    <div class="govuk-button-group">
      <%= form_for cookie_form, as: :cookie, url: cookies_path, method: :post do |f| %>
        <%= f.hidden_field :analytics, value: 'true' %>
        <%= f.hidden_field :return_path, value: path_only(request.url) %>
        <%= f.govuk_submit 'Accept analytics cookies' %>
      <% end %>
      <%= form_for cookie_form, as: :cookie, url: cookies_path, method: :post do |f| %>
        <%= f.hidden_field :analytics, value: 'false' %>
        <%= f.hidden_field :return_path, value: path_only(request.url) %>
        <%= f.govuk_submit 'Reject analytics cookies' %>
      <% end %>
      <%= link_to 'View cookies', cookies_path, class: 'govuk-link' %>
    </div>
  </div>
</div>

app/views/layouts/_cookie_banner_confirmation.html.erb
<div class="govuk-cookie-banner confirmation" role="region" aria-label="Cookies on <%= service_name %>">
  <div class="govuk-cookie-banner__message govuk-width-container" role="alert">

    <div class="govuk-grid-row">
      <div class="govuk-grid-column-two-thirds">

        <div class="govuk-cookie-banner__content">
          <p><%= message %> You can <%= link_to 'change your cookie settings', cookies_path %> at any time.</p>
        </div>
      </div>
    </div>

    <div class="govuk-button-group">
      <form action="<%= request.url %>" method="get">
        <button class="govuk-button" data-module="govuk-button">
          Hide this message
        </button>
      </form>
    </div>
  </div>
</div>

app/views/layouts/_test_message.html.erb
<div class="govuk-notification-banner" role="region" aria-labelledby="govuk-notification-banner-title" data-module="govuk-notification-banner">
  <div class="govuk-notification-banner__header">
    <h2 class="govuk-notification-banner__title" id="govuk-notification-banner-title">
      Important
    </h2>
  </div>
  <div class="govuk-notification-banner__content">
    <p class="govuk-notification-banner__heading">
        <%= t("test.message_html") %>
    </p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" class="govuk-template">
  <head>
    <title><%= [yield(:page_title).presence, t('service.name')].compact.join(' - ') %></title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= tag :meta, name: 'viewport', content: 'width=device-width, initial-scale=1' %>
    <%= tag :meta, property: 'og:image', content: asset_path('images/govuk-opengraph-image.png') %>
    <%= tag :meta, name: 'theme-color', content: '#0b0c0c' %>
    <%= favicon_link_tag asset_path('images/favicon.ico') %>
    <%= favicon_link_tag asset_path('images/govuk-icon-mask.svg'), rel: 'mask-icon', type: 'image/svg', color: "#0b1c0c" %>
    <%= favicon_link_tag asset_path('images/govuk-icon-180.png'), rel: 'apple-touch-icon', type: 'image/png', size: '180x180' %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    
  </head>

  <body class="govuk-template__body">

    <script>
      document.body.className += ' js-enabled' + ('noModule' in HTMLScriptElement.prototype ? ' govuk-frontend-supported' : '');
    </script>

    <%= render partial: 'layouts/cookie_banner' unless cookie_settings['confirmed'] %>

    <% if flash[:cookie_banner_confirmation].present? %>
      <%= render partial: 'layouts/cookie_banner_confirmation', locals: { message: flash[:cookie_banner_confirmation] } %>
    <% end %>

    <%= govuk_skip_link %>

    <%= govuk_header(service_name: t('service.name')) do |header| %>
    <% end %>

    <div class="govuk-width-container">
      <div class="govuk-phase-banner">
        <p class="govuk-phase-banner__content">
          <strong class="govuk-tag govuk-phase-banner__content__tag ">Beta</strong>
          <span class="govuk-phase-banner__text">
            <%= t(".phase_text_html", feedback_link: feedback_link("feedback")) %>
          </span>
        </p>
      </div>
      <main class="govuk-main-wrapper" id="main-content" role="main">
        <%= render 'layouts/test_message' if test_message.present? %>
        <%= yield %>
      </main>
    </div>

    <footer class="govuk-footer " role="contentinfo">
      <div class="govuk-width-container ">
        <div class="govuk-footer__meta">
          <div class="govuk-footer__meta-item govuk-footer__meta-item--grow">
            <h2 class="govuk-visually-hidden">Support links</h2>
            <ul class="govuk-footer__inline-list">
              <li class="govuk-footer__inline-list-item">
                <%= link_to t(".cookies"), cookies_path, class: "govuk-footer__link" %>
              </li>
              <li class="govuk-footer__inline-list-item">
                <%= link_to t(".accessibility_link"), "/pages/accessibility", class: "govuk-footer__link" %>
              </li>
              <li class="govuk-footer__inline-list-item" style="display:none;">
                <%= link_to t(".performance_link"), "/pages/performance", class: "govuk-footer__link" %>
              </li>
            </ul>
            <svg role="presentation" focusable="false" class="govuk-footer__licence-logo" xmlns="http://www.w3.org/2000/svg" viewbox="0 0 483.2 195.7" height="17" width="41">
              <path fill="currentColor" d="M421.5 142.8V.1l-50.7 32.3v161.1h112.4v-50.7zm-122.3-9.6A47.12 47.12 0 0 1 221 97.8c0-26 21.1-47.1 47.1-47.1 16.7 0 31.4 8.7 39.7 21.8l42.7-27.2A97.63 97.63 0 0 0 268.1 0c-36.5 0-68.3 20.1-85.1 49.7A98 98 0 0 0 97.8 0C43.9 0 0 43.9 0 97.8s43.9 97.8 97.8 97.8c36.5 0 68.3-20.1 85.1-49.7a97.76 97.76 0 0 0 149.6 25.4l19.4 22.2h3v-87.8h-80l24.3 27.5zM97.8 145c-26 0-47.1-21.1-47.1-47.1s21.1-47.1 47.1-47.1 47.2 21 47.2 47S123.8 145 97.8 145"
              />
            </svg>
            <span class="govuk-footer__licence-description">
              All content is available under the
              <a class="govuk-footer__link" href="https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/" rel="license">Open Government Licence v3.0</a>, except where otherwise stated
            </span>
          </div>
          <div class="govuk-footer__meta-item">
            <a class="govuk-footer__link govuk-footer__copyright-logo" href="https://www.nationalarchives.gov.uk/information-management/re-using-public-sector-information/uk-government-licensing-framework/crown-copyright/">© Crown copyright</a>
          </div>
        </div>
      </div>
    </footer>
    
  </body>
</html>